### ISSUE TITLE
Request - better examples?

### ISSUE THREAD

**Issue by gitcnd** [iq-motion-control/iq-module-communication-python#12]
Any chance you can make us something we can use right away?  Like a raspberry Pi example perhaps?

**Comment by gitcnd** [comment]
P.S. - FYI - all your documentation URLs are broken (e.g. in all the help and PDF files from your website) - e.g. https://www.iq-control.com/firmware

**Comment by iq-matt** [comment]
Hi there!  Sorry for the super late response.  We're migrating the documentation to Read the Docs.  Both of your requests will be addressed then!  Stay tuned.

**Comment by IQ-Malik** [comment]
Hi @gitcnd Please refer to our [Read the Docs API Communications Manual](https://iq-motion-control-iqmotion.readthedocs-hosted.com/en/latest/) for getting started and examples on how to interact with our motor controllers. Hope this helps!
